### ISSUE TITLE
Assigning roles for project members

### ISSUE THREAD

**Issue by Mike-Soft** [venntris/MeGustatorzy#2]
- [x] Krystian

- [x]  Michał S

- [x] Kamil

- [x] Klaudia

- [x] Michał B

- [x] Marek

**Comment by Mike-Soft** [comment]
Front + back

**Comment by KaSliK** [comment]
Full Stack

**Comment by Krystianwojcik** [comment]
FullTestStackOps

**Comment by KaSliK** [comment]
- [ ] erget

**Comment by venntris** [comment]
Frontend and graphic designer

**Comment by fashionparty** [comment]
I prefer working with frontend

**Comment by treflerm** [comment]
Front + Back
